### ISSUE TITLE
Firefox cannot add a group

### ISSUE THREAD

**Issue by xsnrg** [openhab/smarthome#12]
Greetings,

PaperUI will not allow me to create a new group in Firefox.  I am running 172 build from cloudbees.  There is nothing logged in the debug log, just a dead button in the browser.

Creating a group does pop the PaperUI dialogue box in Chrome, and works.

**Comment by dnobel** [comment]
Confirmed. Fixed with PR #14.

**Comment by kaikreuzer** [comment]
#14 has been merged.

**Comment by xsnrg** [comment]
The button flashes now, but the dialogue does not proceed with Firefox on 64 bit Linux.  Firefox is version 38.01.  Is the preference to re-open this ticket, or start a new one?

**Comment by dnobel** [comment]
You can reopen the bug. But I successfully tested it with latest Firefox on 64 Bit Mac OS. Strange :-( ...

**Comment by dnobel** [comment]
Are you sure, that you have the updated version of the Paper UI, that contains the fix? @kaikreuzer is it part of the current openHAB2 version?

**Comment by xsnrg** [comment]
I am using OH2 build #189.  I have not copied in a unique PaperUI element outside of the distribution package.

**Comment by kaikreuzer** [comment]
Hm, last build (which is integrated in openHAB2) is from May 21 :-(
https://openhab.ci.cloudbees.com/job/smarthome/
The build was not configured to automatically run on changes in the repo. I have changed this now, so with the next openHAB 2 build, this change should be included!

**Comment by xsnrg** [comment]
I really do enjoy easy solutions.

**Comment by xsnrg** [comment]
Just confirmed working in latest build.  Will leave closed.  Thanks!
