### ISSUE TITLE
maven failed process

### ISSUE THREAD

**Issue by vsgit19** [openhab/smarthome#7]
I am trying to compile the project into jar using maven.
i get the following error:
Failed to load p2 metadata repository from location http://eclipse.github.io/smarthome/third-party/target/repository

**Comment by kaikreuzer** [comment]
This repo was just a fork of https://github.com/eclipse-archived/smarthome, meant to build openHAB 2.4.
There should be no reason to build it for anybody, I'll hence archive it.
