### ISSUE TITLE
Version 0.6 is shown

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/smarthome#8]
The PaperUI shows "Paper UI - 0.6" in the lower left corner. It should probably better show the current build number there, e.g. 0.8.0.201505061234

**Comment by dnobel** [comment]
It now shows 0.8, but not a build timestamp. It´s a litte bit complicated to get the build timestamp into the html or js code.

**Comment by kaikreuzer** [comment]
Thanks imho ok.
